### ISSUE TITLE
UnconvBench dataset

### ISSUE THREAD

**Issue by ChangwenXu98** [howardwang1997/CrysToGraph#1]
Hi, this is a very interesting work. Do you plan to share the UnconvBench dataset you use?

**Comment by howardwang1997** [comment]
Hi Changwen, thank you for your interest. I am working on some update for the UnconvBench and it will be ready soon in a new repository: https://github.com/howardwang1997/unconvbench. Hopefully this week.

**Comment by ChangwenXu98** [comment]
Thanks!
